spring.application.name=CrudDemo
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent


# TURN OFF THE SPRINGBOOT BANNNER
spring.main.banner-mode=off

# REDUCE LOGGING LEVEL SET LOGGING LEVEL TO WARN
logging.level.root=warn