spring.application.name=CrudDemo
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent


# TURN OFF THE SPRINGBOOT BANNNER
spring.main.banner-mode=off

# REDUCE LOGGING LEVEL SET LOGGING LEVEL TO WARN
logging.level.root=warn


## ADD LOGGING CONFIG TO DISPLAY THE SQL STATEMENTS
logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.orm.jdbc.bind=trace



## auto config table creation: it help to create the table inside the database
##                              this help in two thing 1) first drop the table 2) then it will create the table again
#                                 (this will lead data loss remember );

# if you want to keep the previous data then you have to use : update
spring.jpa.hibernate.ddl-auto=update